site_name: igraph ctypes interface for Python
repo_url: https://github.com/igraph/python-igraph-ctypes

nav:
  - Home: index.md
  - Notes: notes.md
  - API reference:
      - api/types.md
      - api/graph.md
      - api/constructors.md
      - api/paths.md
      - api/io.md

exclude_docs: |
  fragments/

theme:
  name: material

  features:
    - content.action.edit
    - content.code.copy
    - navigation.instant
    - navigation.tracking
    - navigation.footer

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/igraph2
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@igraph

copyright: >
  Copyright &copy; 2003 - 2023 The igraph core team –
  <a href="#__consent">Change cookie settings</a>

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src
          options:
            show_source: false
