"""Type specifications and aliases."""

# This module simply re-exports types from _internal.enums that are meant to
# be used by end users of the library.
#
# TODO(ntamas): maybe this file should be autogenerated as well?

from ._internal.enums import Connectedness
from ._internal.enums import NeighborMode

__all__ = ("Connectedness", "NeighborMode")
