"""Type specifications and aliases."""

# This module simply re-exports types from _internal.types that are meant to
# be used by end users of the library.
#
# TODO(ntamas): maybe this file should be autogenerated as well?

from ._internal.types import (
    BoolArray,
    EdgeLike,
    EdgeSelector,
    IntArray,
    RealArray,
    VertexLike,
    VertexPair,
    VertexSelector,
)

__all__ = (
    "BoolArray",
    "EdgeLike",
    "EdgeSelector",
    "IntArray",
    "RealArray",
    "VertexLike",
    "VertexPair",
    "VertexSelector",
)
